### ISSUE TITLE
compile err on GO1.11

### ISSUE THREAD

**Issue by gallex** [warthog618/gpio#5]
./dio.go:186:19: invalid operation: 1 << (pin & 31) (shift count type int, must be unsigned integer)
./dio.go:242:28: invalid operation: mem[pin.fsel] >> modeShift (shift count type int, must be unsigned integer)
./dio.go:272:33: invalid operation: modeMask << modeShift (shift count type int, must be unsigned integer)
./dio.go:272:69: invalid operation: uint32(mode) << modeShift (shift count type int, must be unsigned integer)
./dio.go:334:47: invalid operation: pullMask << shift (shift count type int, must be unsigned integer)
./dio.go:334:79: invalid operation: uint32(pull) << shift (shift count type int, must be unsigned integer)

**Comment by warthog618** [comment]
Fixed in e90914221aa69e.
